.Dd 22nd August 2022
.Dt KUSAREMKN 1
.Os
.Sh NAME
.Nm KusaReMKN
.Nd Great Genius Pretty Girl Programming Beginner
.Sh SYNOPSIS
.Nm
.Op Fl l Ar language
.Op Ar
.Sh DESCRIPTION
.Nm
is a corrupt
.Em mikan
that calls herself
.Dq great genius pretty girl programming beginner .
You can call her
.Sy Mikan-chan !
She is a seriously KAWAII girl, plus she has a cock, which is a great deal.
.Pp
By the way, the
.Nm
utility generates a
.Dq insanely cool program
written in the specified language.
Requirements files are required for the generated program.
If
.Ar file
is a single dash
.Pq Ql -
or absent,
.Nm
reads from the standard input.
All these files are passed to Mikan-chan and written to
.Pa /dev/null
by her.
.Pp
The following option is available:
.Bl -tag -width 5n
.It Fl l Ar language
Specifies the language used to write the program.
.El
.Sh FILES
.Bl -tag -width 1234
.It Pa /dev/null
data sink
.El
.Sh EXIT STATUS
.Ex -std
.Sh AUTHORS
.An KusaReMKN Aq https://kusaremkn.com/
.Sh BUGS
Mikan-chan is new to programming and may not be able to write a program
that meets the requirements.
Also, when she is unmotivated,
she may dump core image and give up.
